const el={status:document.querySelector('#status'),pairing:document.querySelector('#pairing'),connected:document.querySelector('#connected'),appUrl:document.querySelector('#app-url'),code:document.querySelector('#pairing-code'),device:document.querySelector('#device-name'),error:document.querySelector('#error')};
const saved=()=>chrome.storage.local.get(['appUrl','deviceToken','deviceId','lastSyncAt','leagueCount']);
const PRODUCTION_ORIGIN='https://fantasy-command-center.acarvall87.workers.dev';
function normalizeUrl(value){const url=new URL(String(value||'').trim());if(url.origin!==PRODUCTION_ORIGIN)throw new Error(`Use ${PRODUCTION_ORIGIN}`);return url.origin}
async function readCookie(name){for(const url of ['https://www.espn.com/','https://fantasy.espn.com/']){const cookie=await chrome.cookies.get({url,name});if(cookie?.value)return cookie.value}return null}
async function sync(){const cfg=await saved();if(!cfg.appUrl||!cfg.deviceToken)throw new Error('Pair this browser first');const[swid,s2]=await Promise.all([readCookie('SWID'),readCookie('espn_s2')]);if(!swid||!s2)throw new Error('Sign into ESPN.com in this browser and try again.');const response=await fetch(`${cfg.appUrl}/api/extension/sync`,{method:'POST',headers:{Authorization:`Bearer ${cfg.deviceToken}`,'Content-Type':'application/json'},body:JSON.stringify({cookies:{swid,s2},reason:'manual_popup'})}),body=await response.json().catch(()=>({}));if(!response.ok){if(response.status===401)await chrome.storage.local.remove(['deviceToken','deviceId']);throw new Error(body?.error?.message||`Sync failed (${response.status})`)}await chrome.storage.local.set({lastSyncAt:new Date().toISOString(),leagueCount:body.leagues?.length||0});return body}
async function pair(){const appUrl=normalizeUrl(el.appUrl.value),code=el.code.value.trim().toUpperCase(),deviceName=el.device.value.trim()||`${navigator.platform||'Browser'} connector`;if(!code)throw new Error('Enter the pairing code from Settings');const response=await fetch(`${appUrl}/api/extension/pair`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code,deviceName})}),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body?.error?.message||`Pairing failed (${response.status})`);await chrome.storage.local.set({appUrl,deviceToken:body.deviceToken,deviceId:body.deviceId});await sync()}
async function disconnect(){const cfg=await saved();if(cfg.appUrl&&cfg.deviceToken)await fetch(`${cfg.appUrl}/api/extension/disconnect`,{method:'DELETE',headers:{Authorization:`Bearer ${cfg.deviceToken}`}}).catch(()=>{});await chrome.storage.local.remove(['deviceToken','deviceId','lastSyncAt','leagueCount'])}
async function render(){el.error.textContent='';const cfg=await saved();el.appUrl.value=cfg.appUrl||'';const connected=Boolean(cfg.appUrl&&cfg.deviceToken);el.pairing.classList.toggle('hidden',connected);el.connected.classList.toggle('hidden',!connected);el.status.textContent=connected?`Paired${cfg.lastSyncAt?` · last sync ${new Date(cfg.lastSyncAt).toLocaleString()}`:''}${cfg.leagueCount!=null?` · ${cfg.leagueCount} league${cfg.leagueCount===1?'':'s'}`:''}`:'Not paired. Generate a one-time code in the app Settings.'}
async function run(action){el.error.textContent='';el.status.textContent='Working…';try{await action()}catch(error){el.error.textContent=error.message}await render()}
document.querySelector('#pair').addEventListener('click',()=>run(pair));document.querySelector('#sync').addEventListener('click',()=>run(sync));document.querySelector('#disconnect').addEventListener('click',()=>run(disconnect));document.querySelector('#open').addEventListener('click',async()=>{const cfg=await saved();if(cfg.appUrl)chrome.tabs.create({url:cfg.appUrl})});render();
