import test from 'node:test';
import assert from 'node:assert/strict';
import { adjustRiskWeights, analyzePlayer, buildScheduleOutlook, comparePlayers, eligibleForSlot, matchupAdjustment, maximizeLegalAssignment, optimizeLineup } from '../src/analysis.js';

test('high DvP percentile is favorable and low percentile is difficult',()=>{assert.ok(matchupAdjustment(95,1)>.1);assert.ok(matchupAdjustment(5,1)<-.1)});
test('adaptive weights protect floor as favorite and seek ceiling as underdog',()=>{const favorite=adjustRiskWeights({floor:.5,median:.1,ceiling:.4},20,true),underdog=adjustRiskWeights({floor:.5,median:.1,ceiling:.4},-20,true);assert.ok(favorite.floor>.5);assert.ok(underdog.ceiling>.4);assert.equal(Math.round((favorite.floor+favorite.median+favorite.ceiling)*100),100)});
test('favorable matchup cannot hide a tiny receiver role',()=>{const player=analyzePlayer({playerId:'1',name:'Receiver',position:'WR',proTeam:'MIA',injuryStatus:'ACTIVE',projectedPoints:10,eligibleSlotIds:[4,23]}, {opponentLookup:{MIA:{opponent:'BUF',game:{eventId:'g1',kickoff:'2099-09-01T17:00:00Z'}}},dvpLookup:{'WR:BUF':{rank:2,percentile:96,grade:'A',confidence:1,generatedAt:'x'}},featureLookup:{'1':{games:8,seasonPpg:9,last3Ppg:9,targetsPerGame:2.7,standardDeviation:3}},weatherLookup:{},riskWeights:{floor:.5,median:.1,ceiling:.4}});assert.ok(player.adjustments.matchup>0);assert.ok(player.warnings.some(w=>w.includes('role')))});
test('slot eligibility supports FLEX',()=>{assert.equal(eligibleForSlot({position:'WR',eligibleSlotIds:[4,23]},23),true);assert.equal(eligibleForSlot({position:'QB',eligibleSlotIds:[0]},23),false)});
test('maximum assignment does not waste the only FLEX-eligible player',()=>{const players=[{playerId:'rb',position:'RB',eligibleSlotIds:[2,23],decisionScore:20},{playerId:'wr',position:'WR',eligibleSlotIds:[4,23],decisionScore:19},{playerId:'te',position:'TE',eligibleSlotIds:[6,23],decisionScore:18}],slots=[{slotId:2},{slotId:23}];const assignment=maximizeLegalAssignment(players,slots);assert.equal(assignment.length,2);assert.equal(new Set(assignment).size,2)});
test('lineup optimizer produces legal unique starters',()=>{const players=[{playerId:'a',name:'A',position:'RB',eligibleSlotIds:[2,23],decisionScore:20},{playerId:'b',name:'B',position:'RB',eligibleSlotIds:[2,23],decisionScore:18},{playerId:'c',name:'C',position:'WR',eligibleSlotIds:[4,23],decisionScore:19},{playerId:'d',name:'D',position:'WR',eligibleSlotIds:[4,23],decisionScore:17}];const result=optimizeLineup(players,{2:1,4:1,23:1,20:3},players,0);assert.equal(result.starters.length,3);assert.equal(new Set(result.starters.map(p=>p.playerId)).size,3);for(const p of result.starters)assert.ok(eligibleForSlot(p,p.assignedSlotId))});
test('schedule outlook distinguishes byes from missing schedule data',()=>{const players=[{playerId:'1',position:'WR',proTeam:'MIA'}],schedule={10:[{homeTeam:'MIA',awayTeam:'BUF'}],11:[]},dvp={'WR:BUF':{percentile:90,grade:'A'}};const result=buildScheduleOutlook(players,schedule,dvp,10,12,[11,12])['1'];assert.equal(result.weeks[0].opponent,'BUF');assert.equal(result.weeks[1].bye,true);assert.equal(result.weeks[2].missingSchedule,true)});
test('comparison labels close calls honestly',()=>{const result=comparePlayers([{playerId:'a',name:'A',decisionScore:10,reasons:[]},{playerId:'b',name:'B',decisionScore:9.5,reasons:[]}]);assert.equal(result.confidence,'close-call');assert.equal(result.recommendation,'a')});
