import { INDOOR_TEAMS, STARTER_SLOT_IDS, BENCH_SLOT_IDS, currentNflSeason, lineupSlotFromId, normalizeTeamAbbreviation, positionFromId, proTeamFromId } from './constants.js';
import { cacheGet, cachePut, getCredentials, saveLeagues, updateCredentialHealth } from './db.js';
import { HttpError } from './http.js';
import { weeklyPlayerStats } from './scoring.js';

const FAN_API='https://fan.api.espn.com/apis/v2/fans';
const LEAGUE_API='https://lm-api-reads.fantasy.espn.com/apis/v3/games/ffl';
const NFL_SCOREBOARD='https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard';
function swid(value){const clean=String(value||'').trim().replace(/[{}]/g,'');return clean?`{${clean}}`:''}
function headers(credentials,filter=null){return{Cookie:`SWID=${swid(credentials.swid)}; espn_s2=${credentials.s2}`,Accept:'application/json','User-Agent':'Mozilla/5.0 FantasyCommandCenter/0.1',...(filter?{'x-fantasy-filter':JSON.stringify(filter)}:{})}}
async function fetchJson(url,options={},label='ESPN'){let response;try{response=await fetch(url,{...options,signal:AbortSignal.timeout(15000)})}catch(error){throw new HttpError(502,'UPSTREAM_UNAVAILABLE',`${label} could not be reached`,{reason:error?.name||'network_error'})}if([401,403].includes(response.status)&&options.headers?.Cookie)throw new HttpError(502,'ESPN_AUTH_EXPIRED','ESPN connection expired. Sign into ESPN in the paired browser and resync.');if(!response.ok)throw new HttpError(502,'ESPN_UPSTREAM_ERROR',`${label} returned ${response.status}`,{upstreamStatus:response.status});try{return await response.json()}catch{throw new HttpError(502,'ESPN_INVALID_RESPONSE',`${label} returned invalid JSON`)}}
export async function discoverEspnLeagues(credentials,{leagueId=null,teamId=null,seasonYear=currentNflSeason()}={}){
  const value=swid(credentials.swid);
  if(!value||!credentials.s2)throw new HttpError(400,'ESPN_CREDENTIALS_REQUIRED','SWID and espn_s2 are required');
  const clean=value.replace(/[{}]/g,'');
  try{
    const body=await fetchJson(`${FAN_API}/${encodeURIComponent(value)}?displayEvents=true`,{headers:{...headers(credentials),'x-p13n-swid':clean,'X-Personalization-Source':'ESPN.com - FAM'}},'ESPN Fan API');
    const leagues=[];
    for(const pref of body.preferences||[]){
      const entry=pref?.metaData?.entry;
      if(pref?.type?.code!=='fantasy'||Number(entry?.gameId)!==1)continue;
      const group=entry?.groups?.[0];
      if(!group?.groupId)continue;
      leagues.push({sport:'football',leagueId:String(group.groupId),leagueName:group.groupName||`League ${group.groupId}`,teamId:String(entry.entryId||''),teamName:entry.entryMetadata?.teamName||'',seasonYear:Number(entry.seasonId||currentNflSeason())});
    }
    if(leagues.length)return leagues;
    throw new HttpError(404,'NO_ESPN_LEAGUES','No ESPN fantasy football leagues were found for this account');
  }catch(error){
    // Account discovery is optional when ESPN grants access to a known league.
    // Never turn an explicit authentication failure into a successful connection.
    if(!leagueId||!['NO_ESPN_LEAGUES','ESPN_UPSTREAM_ERROR','UPSTREAM_UNAVAILABLE','ESPN_INVALID_RESPONSE'].includes(error?.code))throw error;
  }
  const body=await fetchJson(leagueUrl(encodeURIComponent(String(leagueId)),seasonYear,'?view=mSettings&view=mTeam'),{headers:headers(credentials)},'ESPN league API');
  if(String(body.id)!==String(leagueId)||Number(body.seasonId)!==Number(seasonYear))throw new HttpError(502,'ESPN_INVALID_RESPONSE','ESPN returned a different league or season');
  const ownerId=clean.toLowerCase();
  const ownedTeams=(body.teams||[]).filter(team=>(team.owners||[]).some(owner=>swid(owner).slice(1,-1).toLowerCase()===ownerId));
  // A configured team is a roster selection, not an authentication bypass.
  // ESPN has already authorized this league read using the supplied cookies.
  // Only use an explicit selection supplied by trusted Worker configuration.
  const team=teamId!=null?(body.teams||[]).find(candidate=>String(candidate.id)===String(teamId)):(ownedTeams.length===1?ownedTeams[0]:null);
  if(!team)throw new HttpError(409,'ESPN_TEAM_OWNERSHIP_UNVERIFIED',teamId!=null?'The configured team was not found in your ESPN league. Check the selected team ID.':'ESPN granted league access but could not identify your team automatically. Configure your team ID from the ESPN My Team link.');
  if(String(body.id)!==String(leagueId)||Number(body.seasonId)!==Number(seasonYear)||!team.id)throw new HttpError(502,'ESPN_INVALID_RESPONSE','ESPN returned incomplete league information');
  return[{sport:'football',leagueId:String(body.id),seasonYear:Number(body.seasonId),leagueName:body.settings?.name||`League ${body.id}`,teamId:String(team.id),teamName:teamRow(team).name}];
}
export async function discoverAndStoreLeagues(env,credentials){const leagues=await discoverEspnLeagues(credentials);await saveLeagues(env,leagues);await updateCredentialHealth(env,'connected');return leagues}
export async function credentialsOrThrow(env){const value=await getCredentials(env);if(!value?.swid||!value?.s2)throw new HttpError(409,'ESPN_NOT_CONNECTED','Connect ESPN from Settings before using this feature');return value}
function leagueUrl(leagueId,season,query=''){return `${LEAGUE_API}/seasons/${season}/segments/0/leagues/${leagueId}${query}`}
export async function fetchLeagueBundle(env,league,{force=false,week=null}={}){const credentials=await credentialsOrThrow(env);const key=`espn:v2:league:${league.leagueId}:${league.seasonYear}:${week||'current'}`;if(!force){const cached=await cacheGet(env,key);if(cached)return{...cached.value,cache:{stale:false,updatedAt:cached.updatedAt}}}const query=new URLSearchParams();for(const view of ['mSettings','mTeam','mRoster','mMatchup','mMatchupScore','mStatus'])query.append('view',view);if(week!=null)query.set('scoringPeriodId',String(week));try{const body=await fetchJson(leagueUrl(league.leagueId,league.seasonYear,`?${query}`),{headers:headers(credentials)},'ESPN league API');const normalized=normalizeLeagueBundle(body,league,{week});await cachePut(env,key,normalized,180);await updateCredentialHealth(env,'connected');return{...normalized,cache:{stale:false,updatedAt:new Date().toISOString()}}}catch(error){await updateCredentialHealth(env,error?.code==='ESPN_AUTH_EXPIRED'?'expired':'degraded',error?.message||'ESPN request failed');const stale=await cacheGet(env,key,true);if(stale)return{...stale.value,cache:{stale:true,updatedAt:stale.updatedAt,reason:error?.code||'upstream_error'}};throw error}}
function scoringItems(items){return(items||[]).map(item=>({statId:Number(item.statId),points:Number(item.points||0),overrides:Object.entries(item.pointsOverrides||{}).map(([threshold,points])=>({threshold:Number(threshold),points:Number(points)})).filter(x=>Number.isFinite(x.threshold)&&Number.isFinite(x.points))})).filter(item=>Number.isFinite(item.statId)&&Number.isFinite(item.points)).sort((a,b)=>a.statId-b.statId)}
function scoringType(items){const reception=items.find(item=>item.statId===53)||items.find(item=>item.statId===41);const value=Number(reception?.points||0);return value>=.9?'ppr':value>=.4?'half':'standard'}
function rosterEntry(entry,teamId,season,week){const player=entry?.playerPoolEntry?.player;if(!player?.id)return null;const slot=Number(entry.lineupSlotId),stats=weeklyPlayerStats(player,season,week);return{playerId:String(player.id),name:player.fullName||player.displayName||`Player ${player.id}`,position:positionFromId(player.defaultPositionId),defaultPositionId:Number(player.defaultPositionId),eligibleSlotIds:(player.eligibleSlots||[]).map(Number),proTeam:proTeamFromId(player.proTeamId),proTeamId:Number(player.proTeamId||0),injuryStatus:player.injuryStatus||'ACTIVE',lineupSlotId:slot,lineupSlot:lineupSlotFromId(slot),isStarter:STARTER_SLOT_IDS.has(slot),isBench:BENCH_SLOT_IDS.has(slot),...stats,cantCut:player.droppable===false||entry.playerPoolEntry?.droppable===false,status:entry.playerPoolEntry?.status||null,fantasyTeamId:String(teamId||'')}}
function teamRow(team,season,week){return{id:String(team.id),name:team.location&&team.nickname?`${team.location} ${team.nickname}`:team.name||team.abbrev||`Team ${team.id}`,abbreviation:team.abbrev||null,record:team.record?.overall||null,pointsFor:Number(team.record?.overall?.pointsFor||0),pointsAgainst:Number(team.record?.overall?.pointsAgainst||0),playoffSeed:Number(team.playoffSeed||0),roster:(team.roster?.entries||[]).map(entry=>rosterEntry(entry,team.id,season,week)).filter(Boolean)}}
function fantasySchedule(schedule){return(schedule||[]).map(m=>({id:Number(m.id),matchupPeriodId:Number(m.matchupPeriodId||0),winner:m.winner||null,home:m.home?{teamId:String(m.home.teamId||''),totalPoints:Number(m.home.totalPoints||0),totalProjectedPoints:Number(m.home.totalProjectedPoints||0)}:null,away:m.away?{teamId:String(m.away.teamId||''),totalPoints:Number(m.away.totalPoints||0),totalProjectedPoints:Number(m.away.totalProjectedPoints||0)}:null}))}
function currentMatchup(schedule,week,teamId){const matchup=schedule.find(item=>Number(item.matchupPeriodId)===Number(week)&&[String(item.home?.teamId||''),String(item.away?.teamId||'')].includes(String(teamId)));if(!matchup)return null;const home=String(matchup.home?.teamId)===String(teamId),user=home?matchup.home:matchup.away,opponent=home?matchup.away:matchup.home;return{matchupId:matchup.id,userTeamId:String(teamId),opponentTeamId:String(opponent?.teamId||''),userProjectedPoints:Number(user?.totalProjectedPoints||0),opponentProjectedPoints:Number(opponent?.totalProjectedPoints||0),projectionMargin:Number(user?.totalProjectedPoints||0)-Number(opponent?.totalProjectedPoints||0)}}
export function normalizeLeagueBundle(body,stored,{week:requestedWeek=null}={}){const settings=body.settings||{},status=body.status||{},season=Number(body.seasonId||stored.seasonYear),week=Number(requestedWeek||body.scoringPeriodId||status.scoringPeriodId||status.latestScoringPeriod||1),teams=(body.teams||[]).map(team=>teamRow(team,season,week)),schedule=fantasySchedule(body.schedule),items=scoringItems(settings?.scoringSettings?.scoringItems||[]);return{league:{leagueId:String(body.id||stored.leagueId),seasonYear:Number(body.seasonId||stored.seasonYear),leagueName:settings.name||stored.leagueName,teamId:String(stored.teamId),teamName:stored.teamName,currentWeek:week,liveWeek:Number(status.latestScoringPeriod||status.currentMatchupPeriod||body.scoringPeriodId||week),scoringPeriodId:Number(body.scoringPeriodId||status.scoringPeriodId||week),lineupSlotCounts:Object.fromEntries(Object.entries(settings?.rosterSettings?.lineupSlotCounts||{}).map(([id,count])=>[String(id),Number(count)]).filter(([,count])=>count>0)),rosterSize:Object.entries(settings?.rosterSettings?.lineupSlotCounts||{}).filter(([slot])=>Number(slot)!==21&&Number(slot)!==22).reduce((sum,[,count])=>sum+Math.max(0,Number(count)||0),0)||Number(settings?.rosterSettings?.rosterSize||0),scoringItems:items,scoringType:scoringType(items),regularSeasonMatchupCount:Number(settings?.scheduleSettings?.matchupPeriodCount||14),playoffTeamCount:Number(settings?.scheduleSettings?.playoffTeamCount||0)},teams,schedule,currentMatchup:currentMatchup(schedule,week,stored.teamId)}}
export async function fetchFreeAgents(env,league,position=null,count=75,{force=false,week=null}={}){const credentials=await credentialsOrThrow(env);const key=`espn:v2:freeagents:${league.leagueId}:${league.seasonYear}:${week||'current'}:${position||'all'}:${count}`;if(!force){const cached=await cacheGet(env,key);if(cached)return{players:cached.value,cache:{stale:false,updatedAt:cached.updatedAt}}}const slots=position==='QB'?[0]:position==='RB'?[2]:position==='WR'?[4]:position==='TE'?[6]:position==='K'?[17]:position==='D/ST'?[16]:[0,2,4,6,16,17];const filter={players:{filterStatus:{value:['FREEAGENT','WAIVERS']},filterSlotIds:{value:slots},limit:Math.min(Math.max(Number(count),1),150),sortPercOwned:{sortPriority:1,sortAsc:false}}};const url=leagueUrl(league.leagueId,league.seasonYear,`?view=kona_player_info${week?`&scoringPeriodId=${Number(week)}`:''}`);try{const body=await fetchJson(url,{headers:headers(credentials,filter)},'ESPN player API');const players=(body.players||[]).map(item=>{const player=item.player;if(!player?.id)return null;const stats=weeklyPlayerStats(player,league.seasonYear,week||body.scoringPeriodId);return{playerId:String(player.id),name:player.fullName||player.displayName,position:positionFromId(player.defaultPositionId),defaultPositionId:Number(player.defaultPositionId),eligibleSlotIds:(player.eligibleSlots||[]).map(Number),proTeam:proTeamFromId(player.proTeamId),injuryStatus:player.injuryStatus||'ACTIVE',...stats,percentOwned:Number(player.ownership?.percentOwned||0),percentStarted:Number(player.ownership?.percentStarted||0),status:item.status||item.playerPoolEntry?.status||'FREEAGENT',onTeamId:Number(item.onTeamId||0)}}).filter(Boolean).filter(player=>['FREEAGENT','WAIVERS'].includes(player.status));await cachePut(env,key,players,300);return{players,cache:{stale:false,updatedAt:new Date().toISOString()}}}catch(error){const stale=await cacheGet(env,key,true);if(stale)return{players:stale.value,cache:{stale:true,updatedAt:stale.updatedAt}};throw error}}
export async function fetchNflWeekSchedule(env,season,week,{force=false}={}){const key=`nfl:schedule:${season}:${week}`;if(!force){const cached=await cacheGet(env,key);if(cached)return cached.value}const params=new URLSearchParams({dates:String(season),seasontype:'2',week:String(week),limit:'100'});try{const body=await fetchJson(`${NFL_SCOREBOARD}?${params}`,{headers:{Accept:'application/json','User-Agent':'FantasyCommandCenter/0.1'}},'ESPN NFL scoreboard');const games=(body.events||[]).map(event=>{const competition=event?.competitions?.[0],competitors=competition?.competitors||[],home=competitors.find(x=>x.homeAway==='home'),away=competitors.find(x=>x.homeAway==='away'),homeTeam=normalizeTeamAbbreviation(home?.team?.abbreviation),awayTeam=normalizeTeamAbbreviation(away?.team?.abbreviation);if(!homeTeam||!awayTeam)return null;return{eventId:String(event.id),kickoff:event.date||competition?.date||null,homeTeam,awayTeam,indoor:Boolean(competition?.venue?.indoor)||INDOOR_TEAMS.has(homeTeam),venue:competition?.venue?.fullName||null,status:event.status?.type?.state||null}}).filter(Boolean);await cachePut(env,key,games,21600);return games}catch(error){const stale=await cacheGet(env,key,true);if(stale)return stale.value;throw error}}
export function buildOpponentLookup(games){const lookup={};for(const game of games||[]){lookup[game.homeTeam]={opponent:game.awayTeam,game};lookup[game.awayTeam]={opponent:game.homeTeam,game}}return lookup}
export function selectedTeam(bundle){return bundle.teams.find(team=>String(team.id)===String(bundle.league.teamId))||null}
export function selectedOpponent(bundle){return bundle.teams.find(team=>String(team.id)===String(bundle.currentMatchup?.opponentTeamId))||null}
export function allLeaguePlayers(bundle){return bundle.teams.flatMap(team=>team.roster.map(player=>({...player,fantasyTeamId:team.id,fantasyTeamName:team.name}))) }
