const SECURITY_HEADERS=Object.freeze({'Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data: https:; connect-src 'self' https://site.api.espn.com https://fan.api.espn.com https://lm-api-reads.fantasy.espn.com https://api.open-meteo.com; frame-ancestors 'none'; base-uri 'self'; form-action 'self'",'Referrer-Policy':'strict-origin-when-cross-origin','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Permissions-Policy':'camera=(), microphone=(), geolocation=(), payment=()'});
export function json(data,status=200,extraHeaders={}){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...SECURITY_HEADERS,...extraHeaders}})}
export function problem(status,code,message,details=undefined){return json({error:{code,message,...(details===undefined?{}:{details})}},status)}
export function noContent(extraHeaders={}){return new Response(null,{status:204,headers:{...SECURITY_HEADERS,...extraHeaders}})}
export function withHeaders(response,extraHeaders={}){const headers=new Headers(response.headers);for(const [key,value] of Object.entries(extraHeaders))headers.set(key,value);return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}
export function withSecurityHeaders(response){return withHeaders(response,SECURITY_HEADERS)}
export async function readJson(request,maxBytes=64*1024){const contentLength=Number(request.headers.get('content-length')||0);if(contentLength>maxBytes)throw new HttpError(413,'PAYLOAD_TOO_LARGE',`Payload exceeds ${maxBytes} bytes`);const text=await request.text();if(new TextEncoder().encode(text).byteLength>maxBytes)throw new HttpError(413,'PAYLOAD_TOO_LARGE',`Payload exceeds ${maxBytes} bytes`);if(!text)return{};try{return JSON.parse(text)}catch{throw new HttpError(400,'INVALID_JSON','Request body must be valid JSON')}}
export class HttpError extends Error{constructor(status,code,message,details=undefined){super(message);this.name='HttpError';this.status=status;this.code=code;this.details=details}}
export function errorResponse(error){if(error instanceof HttpError)return problem(error.status,error.code,error.message,error.details);console.error('Unhandled request error',sanitizeError(error));return problem(500,'INTERNAL_ERROR','The request could not be completed')}
export function sanitizeError(error){if(!error)return{name:'UnknownError',message:'Unknown error'};const message=String(error.message||error).replace(/espn_s2=[^;\s]+/gi,'espn_s2=[REDACTED]').replace(/SWID=\{?[^;}\s]+\}?/gi,'SWID=[REDACTED]');return{name:error.name||'Error',message,stack:error.stack?String(error.stack).split('\n').slice(0,4).join('\n'):undefined}}
export function parseCookies(request){const out={};const raw=request.headers.get('cookie')||'';for(const item of raw.split(';')){const index=item.indexOf('=');if(index<0)continue;out[item.slice(0,index).trim()]=decodeURIComponent(item.slice(index+1).trim())}return out}
export function corsHeaders(request,allowedMethods='GET,POST,PUT,DELETE,OPTIONS'){const origin=request.headers.get('origin')||'',allowed=origin.startsWith('chrome-extension://')||origin.startsWith('moz-extension://');return{...(allowed?{'Access-Control-Allow-Origin':origin}:{}),'Access-Control-Allow-Methods':allowedMethods,'Access-Control-Allow-Headers':'Authorization, Content-Type','Access-Control-Max-Age':'86400','Vary':'Origin'}}
