import { HttpError, parseCookies } from './http.js';
const encoder=new TextEncoder();const decoder=new TextDecoder();
function b64u(bytes){const binary=Array.from(bytes,b=>String.fromCharCode(b)).join('');return btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'')}
function unb64u(value){const normalized=value.replace(/-/g,'+').replace(/_/g,'/');const padded=normalized+'='.repeat((4-normalized.length%4)%4);return Uint8Array.from(atob(padded),c=>c.charCodeAt(0))}
export function randomToken(bytes=32){const buffer=new Uint8Array(bytes);crypto.getRandomValues(buffer);return b64u(buffer)}
export function randomPairingCode(length=8){const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';const bytes=new Uint8Array(length);crypto.getRandomValues(bytes);return Array.from(bytes,b=>alphabet[b%alphabet.length]).join('')}
export async function sha256(value){const digest=await crypto.subtle.digest('SHA-256',encoder.encode(value));return b64u(new Uint8Array(digest))}
async function importHmacKey(secret){return crypto.subtle.importKey('raw',encoder.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign','verify'])}
export async function constantTimeEqual(a,b){const key=await importHmacKey('fantasy-command-center-constant-time-comparison');const[left,right]=await Promise.all([crypto.subtle.sign('HMAC',key,encoder.encode(String(a))),crypto.subtle.sign('HMAC',key,encoder.encode(String(b)))]);const l=new Uint8Array(left),r=new Uint8Array(right);if(typeof crypto.subtle.timingSafeEqual==='function')return crypto.subtle.timingSafeEqual(l,r);let diff=0;for(let i=0;i<l.length;i++)diff|=l[i]^r[i];return diff===0}
export async function createSessionToken(secret,ttlSeconds=60*60*24*30){if(!secret||secret.length<32)throw new Error('SESSION_SECRET must be at least 32 characters');const now=Math.floor(Date.now()/1000);const payload=b64u(encoder.encode(JSON.stringify({iat:now,exp:now+ttlSeconds,v:1})));const key=await importHmacKey(secret);const signature=new Uint8Array(await crypto.subtle.sign('HMAC',key,encoder.encode(payload)));return `${payload}.${b64u(signature)}`}
export async function verifySessionToken(token,secret){try{const[payload,signature]=String(token||'').split('.');if(!payload||!signature||!secret)return null;const key=await importHmacKey(secret);const valid=await crypto.subtle.verify('HMAC',key,unb64u(signature),encoder.encode(payload));if(!valid)return null;const parsed=JSON.parse(decoder.decode(unb64u(payload)));if(!parsed.exp||parsed.exp<=Math.floor(Date.now()/1000))return null;return parsed}catch{return null}}
export async function requireSession(request,env){const token=parseCookies(request).fcc_session;const session=await verifySessionToken(token,env.SESSION_SECRET);if(!session)throw new HttpError(401,'AUTH_REQUIRED','Sign in to continue');return session}
export function sessionCookie(token,maxAgeSeconds=60*60*24*30,secure=true){return `fcc_session=${encodeURIComponent(token)}; Path=/; HttpOnly${secure?'; Secure':''}; SameSite=Strict; Max-Age=${maxAgeSeconds}`}
export function clearSessionCookie(secure=true){return `fcc_session=; Path=/; HttpOnly${secure?'; Secure':''}; SameSite=Strict; Max-Age=0`}
async function importEncryptionKey(base64Key){if(!base64Key)throw new Error('CREDENTIAL_ENCRYPTION_KEY is not configured');let bytes;try{bytes=Uint8Array.from(atob(base64Key),c=>c.charCodeAt(0))}catch{throw new Error('CREDENTIAL_ENCRYPTION_KEY must be base64 encoded')}if(bytes.byteLength!==32)throw new Error('CREDENTIAL_ENCRYPTION_KEY must decode to exactly 32 bytes');return crypto.subtle.importKey('raw',bytes,'AES-GCM',false,['encrypt','decrypt'])}
export async function encryptJson(value,base64Key){const key=await importEncryptionKey(base64Key);const iv=new Uint8Array(12);crypto.getRandomValues(iv);const plaintext=encoder.encode(JSON.stringify(value));const ciphertext=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,plaintext));return JSON.stringify({v:1,iv:b64u(iv),ciphertext:b64u(ciphertext)})}
export async function decryptJson(envelope,base64Key){const parsed=JSON.parse(envelope);if(parsed.v!==1)throw new Error('Unsupported credential envelope version');const key=await importEncryptionKey(base64Key);const plaintext=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64u(parsed.iv)},key,unb64u(parsed.ciphertext));return JSON.parse(decoder.decode(plaintext))}
export async function requireDevice(request,env){const auth=request.headers.get('authorization')||'';const token=auth.startsWith('Bearer ')?auth.slice(7).trim():'';if(!token)throw new HttpError(401,'DEVICE_AUTH_REQUIRED','Extension device token is required');const tokenHash=await sha256(token);const device=await env.DB.prepare('SELECT id, name, revoked_at FROM devices WHERE token_hash = ?').bind(tokenHash).first();if(!device||device.revoked_at)throw new HttpError(401,'DEVICE_AUTH_INVALID','Extension device token is invalid or revoked');await env.DB.prepare('UPDATE devices SET last_seen_at = CURRENT_TIMESTAMP WHERE id = ?').bind(device.id).run();return device}
export async function requireIngestToken(request,env){const auth=request.headers.get('authorization')||'';const token=auth.startsWith('Bearer ')?auth.slice(7).trim():'';if(!token||!(await constantTimeEqual(token,env.DATA_INGEST_TOKEN||'')))throw new HttpError(401,'INGEST_AUTH_INVALID','Data ingest token is invalid')}
